# Generated by Django 4.1.3 on 2022-11-14 00:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="terms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), size=4
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_year",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_year",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
