# Generated by Django 4.1.3 on 2023-01-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_rename_terms_course_qtrs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["course_number"]},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.CharField(default="My new schedule", max_length=100),
        ),
    ]
